### ISSUE TITLE
1389行 有问题

### ISSUE THREAD

**Issue by yz23095913** [dictlab/mdict-cpp#1]
应该是left=mid吧

**Comment by terasum** [comment]
mid的情况已经单独处理了

**Comment by yz23095913** [comment]
你没有return

**Comment by terasum** [comment]
@yz23095913 我昨天晚上重新测试了一下，在某些情况下二分查找会存在搜索不到的情况，应该是reduce2方法的问题，不是你说的reduce3的问题，我晚上修复一下
