### ISSUE TITLE
Error with Hunspell - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by johannhuang** [dictlab/mdict-cpp#2]
Using the Manually created `makefile`, get the following error.

```
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Undefined symbols for architecture x86_64:
  "Hunspell::stem(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      mdict::Mdict::stem(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in mdict-ae845f.o
  "Hunspell::suggest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      mdict::Mdict::suggest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in mdict-ae845f.o
  "Hunspell::Hunspell(char const*, char const*, char const*)", referenced from:
      mdict::Mdict::Mdict(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in mdict-ae845f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mdict] Error 1
```

By the way, no error with `CMakeLists.txt` method.

My hunspell installed with Homebrew.

```
hunspell --version
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)


Copyright (C) 2002-2014 László Németh. License: MPL/GPL/LGPL.

Based on OpenOffice.org's Myspell library.
Myspell's copyright (C) Kevin Hendricks, 2001-2002, License: BSD.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
```

**Comment by johannhuang** [comment]
I found some hardcoded paths, that could be the reason why it fails but not yet sure.

**Comment by terasum** [comment]
@johannhuang the default hunspell installation by homebrew should be `/usr/local/Cellar/hunspell`, and the Makefile search path is `/usr/local/lib`, you have two choices:
1. modified the `CMakeList.txt` file search path
2. link the hunspell file into `/usr/local/lib/hunspell`

**Comment by terasum** [comment]
@johannhuang if you still have problem, tell me and I'll push a branch without Hunspell lib version, this library is not necessary to search the dictionary content.

**Comment by johannhuang** [comment]
@terasum  the fact is that homebrew has already automatically linked the hunspell to the path `/usr/local/lib/hunspell` as shown bellow.

```sh
ls /usr/local/lib/ | grep hun
libhunspell-1.7.0.dylib
libhunspell-1.7.a
libhunspell-1.7.dylib
```

**Comment by terasum** [comment]
@johannhuang below is my result shows that the hunspell lib has placed the same location as yours.

```
➜  mdict-cpp git:(master) ls /usr/local/lib/ | grep hun
libhunspell-1.7.0.dylib
libhunspell-1.7.a
libhunspell-1.7.dylib
```

And compile successfully.

**Comment by terasum** [comment]
@johannhuang I just tried Cmake and manually Make file to compile the code, both are success, how about try to modify the `LD_LIBRARY_PATH` ?

**Comment by johannhuang** [comment]
Sorry for the later response and even more sorry tho make this issue a little bit personally related. I am up to now not really familiar with the C++ tool chain and still in the process of learning basics. If necessary, I will come back in the future after I get myself clear about this issue. But from now, I guess, there could be something related to the C++ searching path or alike.

**Comment by terasum** [comment]
@johannhuang I've fixed this, libhunspell is an optional library now
