### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_main", referenced from:      implicit entry/start for main executable

### ISSUE THREAD

**Issue by itenyh** [dictlab/mdict-cpp#3]
While I try to make Library With "make mdict",  I got the error:

g++ --std=c++11 -Ideps/miniz/ deps/miniz/miniz.c deps/miniz/miniz_zip.c deps/miniz/miniz_tinfl.c deps/miniz/miniz_tdef.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libmdict] Error 1

No Error with CMake by the way

**Comment by terasum** [comment]
@itenyh I'll take a look later

**Comment by terasum** [comment]
@itenyh just build this by CMAKE, this is a correct way, and the makefile is outdated, I'll fix this later

**Comment by itenyh** [comment]
looking forward to your update

**Comment by terasum** [comment]
@itenyh please use cmake, the make file will be deleted
